version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:

      DATABASE_URL: sqlite:///./data/sql_app.db

    volumes:
      - .:/app
      - sqlite_data:/app/data

  test:
    build: .
    environment:
      DATABASE_URL: sqlite:///./data/test_db.sqlite
    depends_on:
      - app
    volumes:
      - .:/app
      - sqlite_data:/app/data
    command: ["pytest", "tests/"]

volumes:
  sqlite_data: